{{- if and (ne .Values.configuration.modelStorage.type "image") .Values.configuration.hfModelDownload.enabled }}
{{- $token := required "You need to provide a token in .configuration.hfModelDownload.huggingfaceToken if .configuration.hfModelDownload.enabled is set to true" .Values.configuration.hfModelDownload.huggingfaceToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  HUGGING_FACE_HUB_TOKEN: {{ $token | b64enc }}
{{- end }}
